In [1]:
from numpy import exp, array, random, dot

In [70]:
class NeuralNetwork():
    def __init__(self):
        """ Seed the random number generator, so it generates the same
        numbers everytime the program runs."""
        random.seed(1)
        
        """We model a single neuron, with 3 input connections and 1
        output connection.
        We assign random weights to a 3x1 matrix, range -1, 1 and mean 0"""
        self.synaptic_weights = 2*random.random((3,1))-1
        
        """the sigmoid function, will normalize the output between 0 and 1"""
    def sigmoid(self, x):
        return 1/(1 + exp(-x))
        
        """derivative of sigmoid (gradient of sigmoid curve)
        indicates how confident we are about the existing weight"""
    def sigmoid_derivative(self, x):
        return x*(1-x)
        
        """We train our neural network through a process of trial and error
        adjusting the synaptic weights each time"""
    def train(self, training_set_inputs, training_set_ouputs, training_iterations):
        for iteration in range(training_iterations):
                #pass the training set throug our neural network(a single neuron)
            output = self.think(training_set_inputs)
                
                #calculate the error
            error = training_set_outputs - output
                
                #adjust weights by
                # error*input*output*(1-output)
            adjustment = dot(training_set_inputs.T, error*self.sigmoid_derivative(output))
                
                #adjust the weights
            self.synaptic_weights += adjustment
                
                #just print status
            if(iteration%1000==0):
                print('synapsis in iteration \n {}'.format(iteration))
                print(self.synaptic_weights)
        
        #the neural network thinks.
    def think(self, inputs):
            #pass inputs through our neural network
        return self.sigmoid(dot(inputs, self.synaptic_weights))
        
                

In [71]:
neural_network = NeuralNetwork()

print('random starting synaptic weights:\n {}'.format(neural_network.synaptic_weights))

random starting synaptic weights:
 [[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


the training set: 4 examples, each with 3 inputs + 1 output

In [18]:
training_set_inputs = array([[0,0,1],
                             [1,1,1],
                             [1,0,1],
                             [0,1,1]])
training_set_outputs = array([[0,1,1,0]]).T


train the neural network using the training set
do it 10k times

In [72]:
neural_network.train(training_set_inputs, training_set_outputs, 10000)

synapsis in iteration 
 0
[[ 0.12025406]
 [ 0.50456196]
 [-0.85063774]]
synapsis in iteration 
 1000
[[ 7.26390912]
 [-0.21614179]
 [-3.41757429]]
synapsis in iteration 
 2000
[[ 8.00295317]
 [-0.21312397]
 [-3.79003922]]
synapsis in iteration 
 3000
[[ 8.42866725]
 [-0.21151839]
 [-4.00434002]]
synapsis in iteration 
 4000
[[ 8.72838062]
 [-0.21048906]
 [-4.15509467]]
synapsis in iteration 
 5000
[[ 8.95971398]
 [-0.20975712]
 [-4.2713893 ]]
synapsis in iteration 
 6000
[[ 9.14806878]
 [-0.20920202]
 [-4.36603782]]
synapsis in iteration 
 7000
[[ 9.30690067]
 [-0.20876215]
 [-4.44582422]]
synapsis in iteration 
 8000
[[ 9.44420015]
 [-0.20840232]
 [-4.51477526]]
synapsis in iteration 
 9000
[[ 9.56510056]
 [-0.20810078]
 [-4.5754768 ]]


In [73]:
print('New synaptic weights after training')
print (neural_network.synaptic_weights)

New synaptic weights after training
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]


test the neural network with a new situation

In [74]:
print('considering a new situation [1,0,0] -> ?:')
print(neural_network.think(array([1,0,0])))

considering a new situation [1,0,0] -> ?:
[0.99993704]


In [75]:
print('considering a new situation [1,1,1] -> ?:')
print(neural_network.think(array([1,1,1])))

considering a new situation [1,1,1] -> ?:
[0.99211997]


In [76]:
print('considering a new situation [0,0,0] -> ?:')
print(neural_network.think(array([0,0,0])))

considering a new situation [0,0,0] -> ?:
[0.5]


In [77]:
print('considering a new situation [0,1,0] -> ?:')
print(neural_network.think(array([0,1,0])))

considering a new situation [0,1,0] -> ?:
[0.44822538]
